### ISSUE TITLE
Module crashes webpack build due to use of new URL('./', import.meta.url)

### ISSUE THREAD

**Issue by Onekki** [huggingface/transformers.js#984]
### System Info

transformer.js#3

### Environment/Platform

- [ ] Website/web-app
- [X] Browser extension
- [ ] Server-side (e.g., Node.js, Deno, Bun)
- [ ] Desktop app (e.g., Electron)
- [ ] Other (e.g., VSCode extension)

### Description

The dist folder of transformer.js in node_modules contains the "new URL('./', import.meta.url)", which cause a build crash for webpack:
https://github.com/webpack/webpack/issues/16878

### Reproduction

[extension.zip](https://github.com/user-attachments/files/17456422/extension.zip)

**Comment by MrShahzeb-kresus** [comment]
facing thsi issue on expo react native

  "expo": "~51.0.28",
  "react": "18.2.0",
  "react-native": "0.74.5",
  "@xenova/transformers": "^2.17.2",

SyntaxError: 192689:107:'import.meta' is currently unsupported, js engine: hermes [Component Stack]

**Comment by timi137137** [comment]
facing this issue on next v14

    "@huggingface/transformers": "^3.0.0",
    "next": "14.2.5",
    "react": "^18",
    "react-dom": "^18",

```shell
 ⨯ ./node_modules/@huggingface/transformers/dist/transformers.js:32776:1
Module not found: Can't resolve './'
```

**Comment by xenova** [comment]
Hi there 👋 Thanks for reporting - we're working on fixing this :)

In the meantime, there is a workaround as shown [here](https://github.com/huggingface/transformers.js/issues/911#issuecomment-2329440874)
(update the webpack config):
```js
webpack(config, { isServer }) {
	config.resolve.alias['@huggingface/transformers'] = path.resolve(__dirname, 'node_modules/@huggingface/transformers');
        .... 
	return config;
	}
```

**Comment by xenova** [comment]
I might have found a better solution (tested in Next.js v15):
```js
const nextConfig = {
  output: "standalone",
  // https://nextjs.org/docs/app/api-reference/next-config-js/serverExternalPackages
  serverExternalPackages: ["@huggingface/transformers"],
};
```

Let me know if that fixes it!

---

Demo: https://huggingface.co/spaces/webml-community/next-server-template
Source code: https://github.com/huggingface/transformers.js-examples/tree/main/next-server

**Comment by Onekki** [comment]
> Hi there 👋 Thanks for reporting - we're working on fixing this :)
> 
> In the meantime, there is a workaround as shown [here](https://github.com/huggingface/transformers.js/issues/911#issuecomment-2329440874) (update the webpack config):
> 
> ```js
> webpack(config, { isServer }) {
> 	config.resolve.alias['@huggingface/transformers'] = path.resolve(__dirname, 'node_modules/@huggingface/transformers');
>         .... 
> 	return config;
> 	}
> ```

Hi, this config not work for web extension. Although the compilation error is resolved, the browser plugin cannot access the local path when running.

**Comment by Onekki** [comment]
Now, my temporary solution is to copy dist/transformers.js from node_modules into my project and import it directly.

**Comment by rogueturnip** [comment]
I just wanted to say thanks for the suggested fixes.  I'm working with a web worker and the updates to the next.conf.js file don't seem to work for this.

What I'll do is try to convert this to a route and see but I wanted to mention this scenario isn't fixed with the above solutions.

**Comment by augustsaintfreytag** [comment]
The current build of Transformers may work but depending on your Webpack set-up, you have to click through one or two warning overlays telling you that “Accessing import.meta directly is unsupported”. This is definitely questionable for newcomers to the project assuming this is a hard error. Keep in mind that renderer-side errors for Webpack are full-screen blocking overlays, not just something flying by in your terminal.

**Comment by Onekki** [comment]
Solved by referring to the configuration below:

``` javascript
/** @type {import('next').NextConfig} */
import path from "path";
import {fileURLToPath} from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const nextConfig = {
    output: 'export',

    webpack: (config) => {
        config.resolve.alias['@huggingface/transformers'] = path.resolve(__dirname, 'node_modules/@huggingface/transformers');
        config.resolve.alias = {
            ...config.resolve.alias,
            "sharp$": false,
            "onnxruntime-node$": false,
        }
        return config;
    },
};

export default nextConfig;
```
